#!/bin/bash
#
# config.sh
#
# pimt project
#
# definitions
#

# tools
BUCKETSTREAM_ENABLE=1
CERTSTREAM_ENABLE=1
CLOUDENUM_ENABLE=1
SUBFINDER_ENABLE=1
SUBLISTER_ENABLE=1

TOOL_HOME="/opt"

BUCKETSTREAM_HOME=$TOOL_HOME"/bucket-stream"
CERTSTREAM_HOME=$TOOL_HOME
CLOUDENUM_HOME=$TOOL_HOME"/cloud_enum"
SUBLISTER_HOME=$TOOL_HOME"/Sublist3r"

BUCKETSTREAM_BIN=$BUCKETSTREAM_HOME"/bucket-stream.py"
CERTSTREAM_BIN=$CERTSTREAM_HOME"/osint-certstream.py"
CLOUDENUM_BIN=$CLOUDENUM_HOME"/cloud_enum.py"
SUBFINDER_BIN="subfinder"
SUBLISTER_BIN=$SUBLISTER_HOME"/sublist3r.py"

MASSCAN_BIN="masscan"

BUCKETSTREAM="bucketstream"
CERTSTREAM="certstream"
CLOUDENUM="cloudenum"
SUBFINDER=$SUBFINDER_BIN
SUBLISTER="sublister"

MASSCAN=$MASSCAN_BIN

# setup path
export PATH=$PATH:$BUCKETSTREAM_HOME:$CERTSTREAM_HOME:$CLOUDENUM_HOME:$SUBLISTER_HOME
